<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\models\Agencia;
use frontend\models\ReservacionHab;
use frontend\models\Subservicios;
use frontend\models\Servicio;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model frontend\models\Reservacion */

$this->title = 'REPORTES DE AGENCIAS';
$this->params['breadcrumbs'][] = ['label' => 'REPORTES', 'url' => ['agencia']];
$this->params['breadcrumbs'][] = $this->title;
?>

<?php

include 'lib/PHPExcel.php';
include 'lib/PHPExcel/Writer/Excel2007.php';

$objPHPExcel = new PHPExcel();

define('EOL', (PHP_SAPI == 'cli') ? PHP_EOL : '<br />');

$rutaExcel = '//reservas/D/DOCUMENTOS KENIA/ALQUILER/REPORTE SISTEMA/Agencia'." ".$agencia." ".$mes.'.xlsx';
//$rutaExcel = 'E:/Agencia.xlsx';
// Set document properties

$objPHPExcel->getProperties()->setCreator("Sistema de Reservas")
        ->setLastModifiedBy("Sistema de Reservas")
        ->setTitle("Generated by Sistema de Reservas v1.0")
        ->setSubject("Office 2007 XLSX Test Document")
        ->setDescription("Test document for Office 2007 XLSX, generated using PHP classes.")
        ->setKeywords("office 2007 openxml php")
        ->setCategory("Test result file");

// Create a first sheet, representing sales data

$objPHPExcel->setActiveSheetIndex(0);
$objPHPExcel->getActiveSheet()->setCellValue('B1', 'Servicios de Alojamiento');
$objPHPExcel->getActiveSheet()->setCellValue('D1', 'AGENCIA: ' . $agencia);
$objPHPExcel->getActiveSheet()->setCellValue('F1', 'MES: ' . $mes);
$objPHPExcel->getActiveSheet()->getStyle('F1')->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_XLSX15);


//Header de la tabla habria que personalizarlo en depencia del reporte

$objPHPExcel->getActiveSheet()->setCellValue('A3', 'Código');
$objPHPExcel->getActiveSheet()->setCellValue('B3', 'Servicio');
$objPHPExcel->getActiveSheet()->setCellValue('C3', 'Nombre');
$objPHPExcel->getActiveSheet()->setCellValue('D3', 'Fecha Entrada');
$objPHPExcel->getActiveSheet()->setCellValue('E3', 'Cantidad de Habitaciones');
$objPHPExcel->getActiveSheet()->setCellValue('F3', 'Ocupacion');
$objPHPExcel->getActiveSheet()->setCellValue('G3', 'Plan');
$objPHPExcel->getActiveSheet()->setCellValue('H3', 'Precio');
$objPHPExcel->getActiveSheet()->setCellValue('I3', 'Noches');
$objPHPExcel->getActiveSheet()->setCellValue('J3', 'Importe');

$row = 4;
//print_r($alojamientos[0]); die;
for ($i = 0; $i < count($alojamientos); $i++) {
    
    $ent = explode("-", $alojamientos[$i]['fecha']);
    $entrada="";
    if (count($ent)==3) {
        $entrada = $ent[2] . "-" . $ent[1] . "-" . $ent[0];
    }
    
    
    $objPHPExcel->getActiveSheet()->setCellValue('A' . $row, $alojamientos[$i]['codigo']);
    $objPHPExcel->getActiveSheet()->setCellValue('B' . $row, $alojamientos[$i]['servicio']);
    $objPHPExcel->getActiveSheet()->setCellValue('C' . $row, $alojamientos[$i]['nombre']);
    $objPHPExcel->getActiveSheet()->setCellValue('D' . $row, $entrada);
    $objPHPExcel->getActiveSheet()->setCellValue('E' . $row, $alojamientos[$i]['cant']);
    $objPHPExcel->getActiveSheet()->setCellValue('F' . $row, $alojamientos[$i]['ocupacion']);
    $objPHPExcel->getActiveSheet()->setCellValue('G' . $row, $alojamientos[$i]['plan']);
    $objPHPExcel->getActiveSheet()->setCellValue('H' . $row, $alojamientos[$i]['precio']);
    $objPHPExcel->getActiveSheet()->setCellValue('I' . $row, $alojamientos[$i]['noches']);
    $objPHPExcel->getActiveSheet()->setCellValue('J' . $row, $alojamientos[$i]['subtotal']);

    $row++;
}


$objPHPExcel->getActiveSheet()->getProtection()->setSheet(false);    // Needs to be set to true in order to enable any worksheet protection!
$objPHPExcel->getActiveSheet()->protectCells('A3:J' . $row, 'PHPExcel');

// Set cell number formats

$objPHPExcel->getActiveSheet()->getStyle('H4:H' . ($row + 2))->getNumberFormat()->setFormatCode('#,##0.00');
$objPHPExcel->getActiveSheet()->getStyle('J4:J' . ($row + 2))->getNumberFormat()->setFormatCode('#,##0.00');

// Set column widths

$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(28);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(28);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(25);
$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(10);
$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(10);
$objPHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(10);
$objPHPExcel->getActiveSheet()->getColumnDimension('I')->setWidth(10);
$objPHPExcel->getActiveSheet()->getColumnDimension('J')->setWidth(10);

// Set fonts

$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setName('Candara');
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setSize(20);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setUnderline(PHPExcel_Style_Font::UNDERLINE_SINGLE);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('D1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('E1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('D' . ($row + 2))->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('J' . ($row + 2))->getFont()->setBold(true);

// Set thin black border outline around column

$styleThinBlackBorderOutline = array(
    'borders' => array(
        'outline' => array(
            'style' => PHPExcel_Style_Border::BORDER_THIN,
            'color' => array('argb' => 'FF000000'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('A4:J' . ($row - 1))->applyFromArray($styleThinBlackBorderOutline);



$objPHPExcel->getActiveSheet()->getStyle('A1:J1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:J1')->getFill()->getStartColor()->setARGB('FF808080');

// Set style for header row using alternative method

$objPHPExcel->getActiveSheet()->getStyle('A3:J3')->applyFromArray(
        array(
            'font' => array(
                'bold' => true
            ),
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'top' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            ),
            'fill' => array(
                'type' => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
                'rotation' => 90,
                'startcolor' => array(
                    'argb' => 'FFA0A0A0'
                ),
                'endcolor' => array(
                    'argb' => 'FFFFFFFF'
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('A3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'left' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('B3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('J3')->applyFromArray(
        array(
            'borders' => array(
                'right' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);



$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddHeader('&L&BInvoice&RPrinted on &D');
$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');

// Set page orientation and size

$objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);
$objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);

// Rename first worksheet

$objPHPExcel->getActiveSheet()->setTitle('Servicios de Alojamiento');

// Create a new worksheet, after the default sheet

$objPHPExcel->createSheet();

// Create a first sheet, representing sales data

$objPHPExcel->setActiveSheetIndex(1);

// Create a first sheet, representing sales data

$objPHPExcel->getActiveSheet()->setCellValue('B1', 'Servicios Extras Incluidos');
$objPHPExcel->getActiveSheet()->setCellValue('D1', 'AGENCIA: ' . $agencia);
$objPHPExcel->getActiveSheet()->setCellValue('F1', 'MES: ' . $mes);
$objPHPExcel->getActiveSheet()->getStyle('D1')->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_XLSX15);
//Header de la tabla habria que personalizarlo en depencia del reporte


$objPHPExcel->getActiveSheet()->setCellValue('A3', 'Fecha');
$objPHPExcel->getActiveSheet()->setCellValue('B3', 'Nombre');
$objPHPExcel->getActiveSheet()->setCellValue('C3', 'Tipo Servicio');
$objPHPExcel->getActiveSheet()->setCellValue('D3', 'Nombre Servicio');
$objPHPExcel->getActiveSheet()->setCellValue('E3', 'Cantidad');
$objPHPExcel->getActiveSheet()->setCellValue('F3', 'Precio');
$objPHPExcel->getActiveSheet()->setCellValue('G3', 'Sub total');
//$objPHPExcel->getActiveSheet()->setCellValue('H3', 'Noches');
//$objPHPExcel->getActiveSheet()->setCellValue('I3', 'Importe');

$row = 4;

for ($i = 0; $i < count($incluidos); $i++) {

    $objPHPExcel->getActiveSheet()->setCellValue('A' . $row, $incluidos[$i]['fecha']);
    $objPHPExcel->getActiveSheet()->setCellValue('B' . $row, $incluidos[$i]['nombre']);
    $objPHPExcel->getActiveSheet()->setCellValue('C' . $row, $incluidos[$i]['servicio']);
    $objPHPExcel->getActiveSheet()->setCellValue('D' . $row, $incluidos[$i]['nombre_servicio']);
    $objPHPExcel->getActiveSheet()->setCellValue('E' . $row, $incluidos[$i]['cantidad']);
    $objPHPExcel->getActiveSheet()->setCellValue('F' . $row, $incluidos[$i]['precio']);
    $objPHPExcel->getActiveSheet()->setCellValue('G' . $row, $incluidos[$i]['subtotal']);
    //print_r($incluidos[$i]['precio']);die;
    $row++;
}

/*

  $objPHPExcel->getActiveSheet()->setCellValue('F'.($row), 'Total excl.:');
  $objPHPExcel->getActiveSheet()->setCellValue('G'.($row), '=SUM(I4:I'.($row-1).')');

  $objPHPExcel->getActiveSheet()->setCellValue('F'.($row+1), 'VAT:');
  $objPHPExcel->getActiveSheet()->setCellValue('G'.($row+1), '=I'. ($row) .'*0.21');

  $objPHPExcel->getActiveSheet()->setCellValue('F'.($row+2), 'Total incl.:');
  $objPHPExcel->getActiveSheet()->setCellValue('G'.($row+2), '=I'.($row).'+I'.($row+1).'');
 */
// Protect cells

$objPHPExcel->getActiveSheet()->getProtection()->setSheet(true);    // Needs to be set to true in order to enable any worksheet protection!
$objPHPExcel->getActiveSheet()->protectCells('A3:G' . $row, 'PHPExcel');

// Set cell number formats

//$objPHPExcel->getActiveSheet()->getStyle('G4:G' . ($row + 2))->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);

$objPHPExcel->getActiveSheet()->getStyle('G4:G' . ($row + 2))->getNumberFormat()->setFormatCode('#,##0.00');
$objPHPExcel->getActiveSheet()->getStyle('F4:F' . ($row + 2))->getNumberFormat()->setFormatCode('#,##0.00');
// Set column widths

$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(28);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(20);
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(10);
$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(10);
$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(10);

// Set fonts

$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setName('Candara');
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setSize(20);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setUnderline(PHPExcel_Style_Font::UNDERLINE_SINGLE);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('D1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('E1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('D' . ($row + 2))->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('G' . ($row + 2))->getFont()->setBold(true);

// Set thin black border outline around column

$styleThinBlackBorderOutline = array(
    'borders' => array(
        'outline' => array(
            'style' => PHPExcel_Style_Border::BORDER_THIN,
            'color' => array('argb' => 'FF000000'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('A4:G' . ($row - 1))->applyFromArray($styleThinBlackBorderOutline);

// Set thick brown border outline around "Total"
/*
  $styleThickBrownBorderOutline = array(
  'borders' => array(
  'outline' => array(
  'style' => PHPExcel_Style_Border::BORDER_THICK,
  'color' => array('argb' => 'FF993300'),
  ),
  ),
  );
  $objPHPExcel->getActiveSheet()->getStyle('F'.($row+2).':G'.($row+2))->applyFromArray($styleThickBrownBorderOutline);
 */
// Set fills

$objPHPExcel->getActiveSheet()->getStyle('A1:G1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:G1')->getFill()->getStartColor()->setARGB('FF808080');

// Set style for header row using alternative method

$objPHPExcel->getActiveSheet()->getStyle('A3:G3')->applyFromArray(
        array(
            'font' => array(
                'bold' => true
            ),
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'top' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            ),
            'fill' => array(
                'type' => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
                'rotation' => 90,
                'startcolor' => array(
                    'argb' => 'FFA0A0A0'
                ),
                'endcolor' => array(
                    'argb' => 'FFFFFFFF'
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('A3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'left' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('B3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('G3')->applyFromArray(
        array(
            'borders' => array(
                'right' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);



// Set header and footer. When no different headers for odd/even are used, odd header is assumed.

$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddHeader('&L&BInvoice&RPrinted on &D');
$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');

// Set page orientation and size

$objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);
$objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);

$objPHPExcel->getActiveSheet()->setTitle('Servicios Extras Incluidos');


// Set active sheet index to the first sheet, so Excel opens this as the first sheet
$objPHPExcel->setActiveSheetIndex(0);






$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
$objWriter->save($rutaExcel);

echo ' <div class="alert bg-green alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                                Se ha creado el Excel de Reporte Agencia en la siguiente Ruta <strong>' . $rutaExcel . '</strong><br>
                                <a style="color:white;" href="' . Yii::$app->urlManager->createAbsoluteUrl('reportes/agencia') . '"><strong>Volver a Resportes Agencias</strong></a>
                            </div> ', EOL;
?>