<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\models\Agencia;
use frontend\models\ReservacionHab;
use frontend\models\Subservicios;
use frontend\models\Servicio;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model frontend\models\Reservacion */

$this->title = 'REPORTES DE INGRESOS';
$this->params['breadcrumbs'][] = ['label' => 'REPORTES', 'url' => ['ingrsos']];
$this->params['breadcrumbs'][] = $this->title;
?>

<?php

include 'lib/PHPExcel.php';
include 'lib/PHPExcel/Writer/Excel2007.php';

$objPHPExcel = new PHPExcel();

define('EOL', (PHP_SAPI == 'cli') ? PHP_EOL : '<br />');

$rutaExcel = '//reservas/D/DOCUMENTOS KENIA/ALQUILER/REPORTE SISTEMA/Ingesos ' . $entrada . ' hasta ' . $salida . '.xlsx';
//$rutaExcel = 'E:/Ingesos ' . $entrada . ' hasta ' . $salida . '.xlsx';

// Set document properties

$objPHPExcel->getProperties()->setCreator("Sistema de Reservas")
        ->setLastModifiedBy("Sistema de Reservas")
        ->setTitle("Generated by Sistema de Reservas v1.0")
        ->setSubject("Office 2007 XLSX Test Document")
        ->setDescription("Test document for Office 2007 XLSX, generated using PHP classes.")
        ->setKeywords("office 2007 openxml php")
        ->setCategory("Test result file");

// Create a first sheet, representing sales data


$fecha = explode('-', $entrada);
$entrada = $fecha[2] . '-' . $fecha[1] . '-' . $fecha[0];


$fecha = explode('-', $salida);
$salida = $fecha[2] . '-' . $fecha[1] . '-' . $fecha[0];



$objPHPExcel->setActiveSheetIndex(0);
$objPHPExcel->getActiveSheet()->setCellValue('B1', 'INGRESOS');
$objPHPExcel->getActiveSheet()->setCellValue('D1', 'FECHA INICIAL: ' . $entrada . ' FECHA FINAL: ' . $salida);
$objPHPExcel->getActiveSheet()->getStyle('H1')->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_XLSX15);

$objPHPExcel->getActiveSheet()->mergeCells('B1:C1');
$objPHPExcel->getActiveSheet()->mergeCells('D1:H1');

//Header de la tabla habria que personalizarlo en depencia del reporte

$objPHPExcel->getActiveSheet()->setCellValue('A3', 'Nombre Cliente');
$objPHPExcel->getActiveSheet()->setCellValue('B3', 'Agencia');
$objPHPExcel->getActiveSheet()->setCellValue('C3', 'Fecha');
$objPHPExcel->getActiveSheet()->setCellValue('D3', 'Noches');
$objPHPExcel->getActiveSheet()->setCellValue('E3', 'Cantidad / Hab');
$objPHPExcel->getActiveSheet()->setCellValue('F3', 'Importe Alojamiento');
$objPHPExcel->getActiveSheet()->setCellValue('G3', 'Importe Servicios');
$objPHPExcel->getActiveSheet()->setCellValue('H3', 'Importe Total');

$row = 4;
$suma_aloj = 0;
$suma_ser = 0;
$suma_total = 0;

//print_r($resultado);die;

for ($i = 0; $i < count($resultado); $i++) {
    $objPHPExcel->getActiveSheet()->setCellValue('A' . $row, $resultado[$i]['nombre']);
    $objPHPExcel->getActiveSheet()->setCellValue('B' . $row, $resultado[$i]['agencia']);
    $objPHPExcel->getActiveSheet()->setCellValue('C' . $row, $resultado[$i]['fecha']);
    $objPHPExcel->getActiveSheet()->setCellValue('D' . $row, $resultado[$i]['noches']);
    $objPHPExcel->getActiveSheet()->setCellValue('E' . $row, $resultado[$i]['canthab']);
    $objPHPExcel->getActiveSheet()->setCellValue('F' . $row, Yii::$app->formatter->asDecimal($resultado[$i]['imp_aloj'], 2));
    $objPHPExcel->getActiveSheet()->setCellValue('G' . $row, Yii::$app->formatter->asDecimal($resultado[$i]['imp_ser'], 2));
    $objPHPExcel->getActiveSheet()->setCellValue('H' . $row, Yii::$app->formatter->asDecimal($resultado[$i]['imp_ser'] + $resultado[$i]['imp_aloj'], 2));

    $row++;

    $suma_aloj = $suma_aloj + $resultado[$i]['imp_aloj'];
    $suma_ser = $suma_ser + $resultado[$i]['imp_ser'];
    $suma_total = $suma_total + $resultado[$i]['imp_ser'] + $resultado[$i]['imp_aloj'];
}

$objPHPExcel->getActiveSheet()->setCellValue('A' . $row, '');
$objPHPExcel->getActiveSheet()->setCellValue('B' . $row, '');
$objPHPExcel->getActiveSheet()->setCellValue('C' . $row, '');
$objPHPExcel->getActiveSheet()->setCellValue('D' . $row, '');
$objPHPExcel->getActiveSheet()->setCellValue('E' . $row, '');
$objPHPExcel->getActiveSheet()->setCellValue('F' . $row, Yii::$app->formatter->asDecimal($suma_aloj, 2));
$objPHPExcel->getActiveSheet()->setCellValue('G' . $row, Yii::$app->formatter->asDecimal($suma_ser, 2));
$objPHPExcel->getActiveSheet()->setCellValue('H' . $row, Yii::$app->formatter->asDecimal($suma_total, 2));

/*
  $objPHPExcel->getActiveSheet()->setCellValue('H'.($row), 'Total excl.:');
  $objPHPExcel->getActiveSheet()->setCellValue('I'.($row), '=SUM(I4:I'.($row-1).')');

  $objPHPExcel->getActiveSheet()->setCellValue('H'.($row+1), 'VAT:');
  $objPHPExcel->getActiveSheet()->setCellValue('I'.($row+1), '=I'. ($row) .'*0.21');

  $objPHPExcel->getActiveSheet()->setCellValue('H'.($row+2), 'Total incl.:');
  $objPHPExcel->getActiveSheet()->setCellValue('I'.($row+2), '=I'.($row).'+I'.($row+1).'');
 */
// Protect cells

$objPHPExcel->getActiveSheet()->getProtection()->setSheet(false);    // Needs to be set to true in order to enable any worksheet protection!
$objPHPExcel->getActiveSheet()->protectCells('A3:H' . $row, 'PHPExcel');

// Set cell number formats

$objPHPExcel->getActiveSheet()->getStyle('I4:J' . ($row + 2))->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);

// Set column widths

$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(35);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(20);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(12);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(12);
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(19);
$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(20);
$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(15);

// Set fonts

$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setName('Candara');
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setSize(20);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setUnderline(PHPExcel_Style_Font::UNDERLINE_SINGLE);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('D1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('H' . ($row + 2))->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('H' . ($row + 2))->getFont()->setBold(true);

// Set thin black border outline around column

$styleThinBlackBorderOutline = array(
    'borders' => array(
        'outline' => array(
            'style' => PHPExcel_Style_Border::BORDER_THIN,
            'color' => array('argb' => 'FF000000'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('A4:H' . ($row))->applyFromArray($styleThinBlackBorderOutline);

// Set thick brown border outline around "Total"
/*
  $styleThickBrownBorderOutline = array(
  'borders' => array(
  'outline' => array(
  'style' => PHPExcel_Style_Border::BORDER_THICK,
  'color' => array('argb' => 'FF993300'),
  ),
  ),
  );
  $objPHPExcel->getActiveSheet()->getStyle('H'.($row+2).':I'.($row+2))->applyFromArray($styleThickBrownBorderOutline);
 */
// Set fills

$objPHPExcel->getActiveSheet()->getStyle('A1:H1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:H1')->getFill()->getStartColor()->setARGB('FF808080');

// Set style for header row using alternative method




/* ESTO ES PARA Q MI TABLA SE LE MUESTRE TODOS LOS BORDES DE LA CELDA */


$cuerpo = array(
    'borders' => array(
        'allborders' => array(
            'style' => PHPExcel_Style_Border::BORDER_THIN,
            'color' => array('argb' => 'FF000000'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('A3:H' . ($row - 1))->applyFromArray($cuerpo);

/* * **************************************------------********************** */




$objPHPExcel->getActiveSheet()->getStyle('A3:H' . $row)->applyFromArray(
        /* ESTO ES PARA QUE LAS LETRAS SE PONGAN NEGRITAS */
        array(
            'font' => array(
                'bold' => true
            ),
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'top' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);

// Add a drawing to the worksheet

$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Logo');
$objDrawing->setDescription('Logo');
$objDrawing->setPath('./images/logo.png');
$objDrawing->setHeight(36);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());



// Set header and footer. When no different headers for odd/even are used, odd header is assumed.

$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddHeader('&L&BInvoice&RPrinted on &D');
$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');

// Set page orientation and size

$objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);
$objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);

// Rename first worksheet

$objPHPExcel->getActiveSheet()->setTitle('INGRESOS RESERVACIONES');







$objPHPExcel->createSheet();
$objPHPExcel->setActiveSheetIndex(1);

$objPHPExcel->getActiveSheet()->setCellValue('B1', 'INGRESOS');
$objPHPExcel->getActiveSheet()->setCellValue('C1', 'FECHA INICIAL: ' . $entrada . ' FECHA FINAL: ' . $salida);
$objPHPExcel->getActiveSheet()->getStyle('E1')->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_XLSX15);

//$objPHPExcel->getActiveSheet()->mergeCells('B1:C1');
$objPHPExcel->getActiveSheet()->mergeCells('C1:E1');

//Header de la tabla habria que personalizarlo en depencia del reporte

$objPHPExcel->getActiveSheet()->setCellValue('A3', 'Nombre Servicio');
$objPHPExcel->getActiveSheet()->setCellValue('B3', 'Agencia');
$objPHPExcel->getActiveSheet()->setCellValue('C3', 'Fecha');
$objPHPExcel->getActiveSheet()->setCellValue('D3', 'Cantidad ');
$objPHPExcel->getActiveSheet()->setCellValue('E3', 'Importe Total');




$row = 4;
$sum = 0;
//echo count($alojamientos); die;
for ($i = 0; $i < count($pasadia); $i++) {
    $objPHPExcel->getActiveSheet()->setCellValue('A' . $row, $pasadia[$i]['nombre']);
    $objPHPExcel->getActiveSheet()->setCellValue('B' . $row, $pasadia[$i]['agencia']);
    $objPHPExcel->getActiveSheet()->setCellValue('C' . $row, $pasadia[$i]['fecha']);
    $objPHPExcel->getActiveSheet()->setCellValue('D' . $row, $pasadia[$i]['canthab']);
    $objPHPExcel->getActiveSheet()->setCellValue('E' . $row, Yii::$app->formatter->asDecimal($pasadia[$i]['imp_ser'], 2));
    $sum = $sum + $pasadia[$i]['imp_ser'];
    $row++;
}

$objPHPExcel->getActiveSheet()->setCellValue('A' . $row, '');
$objPHPExcel->getActiveSheet()->setCellValue('B' . $row, '');
$objPHPExcel->getActiveSheet()->setCellValue('C' . $row, '');
$objPHPExcel->getActiveSheet()->setCellValue('D' . $row, '');
$objPHPExcel->getActiveSheet()->setCellValue('E' . $row, $sum);

/*
  $objPHPExcel->getActiveSheet()->setCellValue('H'.($row), 'Total excl.:');
  $objPHPExcel->getActiveSheet()->setCellValue('I'.($row), '=SUM(I4:I'.($row-1).')');

  $objPHPExcel->getActiveSheet()->setCellValue('H'.($row+1), 'VAT:');
  $objPHPExcel->getActiveSheet()->setCellValue('I'.($row+1), '=I'. ($row) .'*0.21');

  $objPHPExcel->getActiveSheet()->setCellValue('H'.($row+2), 'Total incl.:');
  $objPHPExcel->getActiveSheet()->setCellValue('I'.($row+2), '=I'.($row).'+I'.($row+1).'');
 */
// Protect cells

$objPHPExcel->getActiveSheet()->getProtection()->setSheet(false);    // Needs to be set to true in order to enable any worksheet protection!
$objPHPExcel->getActiveSheet()->protectCells('A3:E' . $row, 'PHPExcel');

// Set cell number formats

$objPHPExcel->getActiveSheet()->getStyle('I4:J' . ($row + 2))->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);

// Set column widths

$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(40);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(25);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(14);
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(19);

// Set fonts

$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setName('Candara');
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setSize(20);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setUnderline(PHPExcel_Style_Font::UNDERLINE_SINGLE);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('D1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('E' . ($row + 2))->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('E' . ($row + 2))->getFont()->setBold(true);

// Set thin black border outline around column

$styleThinBlackBorderOutline = array(
    'borders' => array(
        'outline' => array(
            'style' => PHPExcel_Style_Border::BORDER_THIN,
            'color' => array('argb' => 'FF000000'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('A4:E' . ($row))->applyFromArray($styleThinBlackBorderOutline);

// Set thick brown border outline around "Total"
/*
  $styleThickBrownBorderOutline = array(
  'borders' => array(
  'outline' => array(
  'style' => PHPExcel_Style_Border::BORDER_THICK,
  'color' => array('argb' => 'FF993300'),
  ),
  ),
  );
  $objPHPExcel->getActiveSheet()->getStyle('H'.($row+2).':I'.($row+2))->applyFromArray($styleThickBrownBorderOutline);
 */
// Set fills

$objPHPExcel->getActiveSheet()->getStyle('A1:E1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:E1')->getFill()->getStartColor()->setARGB('FF808080');

// Set style for header row using alternative method




/* ESTO ES PARA Q MI TABLA SE LE MUESTRE TODOS LOS BORDES DE LA CELDA */


$cuerpo = array(
    'borders' => array(
        'allborders' => array(
            'style' => PHPExcel_Style_Border::BORDER_THIN,
            'color' => array('argb' => 'FF000000'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('A3:E' . ($row - 1))->applyFromArray($cuerpo);

/* * **************************************------------********************** */




$objPHPExcel->getActiveSheet()->getStyle('A3:E' . $row)->applyFromArray(
        /* ESTO ES PARA QUE LAS LETRAS SE PONGAN NEGRITAS */
        array(
            'font' => array(
                'bold' => true
            ),
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'top' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);

// Add a drawing to the worksheet

$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Logo');
$objDrawing->setDescription('Logo');
$objDrawing->setPath('./images/logo.png');
$objDrawing->setHeight(36);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());



// Set header and footer. When no different headers for odd/even are used, odd header is assumed.

$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddHeader('&L&BInvoice&RPrinted on &D');
$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');

// Set page orientation and size

$objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);
$objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);


$objPHPExcel->getActiveSheet()->setTitle('INGRESOS PASADIA');






$objPHPExcel->setActiveSheetIndex(0);
$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
$objWriter->save($rutaExcel);

echo ' <div class="alert bg-green alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                                Se ha creado el Excel de Reporte Ingresos en la siguiente Ruta <strong>' . $rutaExcel . '</strong><br>
                                <a style="color:white;" href="' . Yii::$app->urlManager->createAbsoluteUrl('reportes/ingresos') . '"><strong>Volver a Resportes Ingesos</strong></a>
                            </div> ', EOL;
?>