



<?php

$this->title = 'REPORTES DE TRABAJADORES';
$this->params['breadcrumbs'][] = ['label' => 'TRABAJADORES', 'url' => ['trabajador']];
$this->params['breadcrumbs'][] = $this->title;
?>


<?php

include 'lib/PHPExcel.php';
include 'lib/PHPExcel/Writer/Excel2007.php';

$objPHPExcel = new PHPExcel();

define('EOL', (PHP_SAPI == 'cli') ? PHP_EOL : '<br />');

//$rutaExcel = 'D:/DOCUMENTOS KENIA/ALQUILER/REPORTE SISTEMA/TRABAJADORES.xlsx';
$rutaExcel = '//reservas/D/DOCUMENTOS KENIA/ALQUILER/REPORTE SISTEMA/TRABAJADORES'." ".$meses.'.xlsx';
//$rutaExcel = 'E:/TRABAJADORES.xlsx';

// Set document properties

$objPHPExcel->getProperties()->setCreator("Sistema de Reservas")
        ->setLastModifiedBy("Sistema de Reservas")
        ->setTitle("Generated by Sistema de Reservas v1.0")
        ->setSubject("Office 2007 XLSX Test Document")
        ->setDescription("Test document for Office 2007 XLSX, generated using PHP classes.")
        ->setKeywords("office 2007 openxml php")
        ->setCategory("Test result file");

// Create a first sheet, representing sales data



$objPHPExcel->setActiveSheetIndex(0);
$objPHPExcel->getActiveSheet()->setCellValue('B1', 'REPORTE DE TRABAJADORES');
$objPHPExcel->getActiveSheet()->setCellValue('C1', 'FECHA : ' . $meses);
$objPHPExcel->getActiveSheet()->getStyle('F1')->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_XLSX15);

$objPHPExcel->getActiveSheet()->setCellValue('A3', 'Nombre');
$objPHPExcel->getActiveSheet()->setCellValue('B3', 'Dpto');
$objPHPExcel->getActiveSheet()->setCellValue('C3', 'Salario');

$row = 4;
$total = 0;
//echo count($alojamientos); die;
for ($i = 0; $i < count($trabajador); $i++) {

    $objPHPExcel->getActiveSheet()->setCellValue('A' . $row, $trabajador[$i]['nombre']);
    $objPHPExcel->getActiveSheet()->setCellValue('B' . $row, $trabajador[$i]['dpto']);
    $objPHPExcel->getActiveSheet()->setCellValue('C' . $row, Yii::$app->formatter->asDecimal($trabajador[$i]['salario'], 2));
    $total+=$trabajador[$i]['salario'];
    $row++;
}
$objPHPExcel->getActiveSheet()->setCellValue('A' . $row, '');
$objPHPExcel->getActiveSheet()->setCellValue('B' . $row,'TOTAL');
$objPHPExcel->getActiveSheet()->setCellValue('C' . $row,$total);

$row++;




$objPHPExcel->getActiveSheet()->getProtection()->setSheet(false);    // Needs to be set to true in order to enable any worksheet protection!
$objPHPExcel->getActiveSheet()->protectCells('A3:C' . $row, 'PHPExcel');

// Set cell number formats

$objPHPExcel->getActiveSheet()->getStyle('I4:J' . ($row + 2))->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);

// Set column widths

$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(28);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(32);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(15);

// Set fonts

$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setName('Candara');
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setSize(12);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setUnderline(PHPExcel_Style_Font::UNDERLINE_SINGLE);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);


$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('C' . ($row + 2))->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('C' . ($row + 2))->getFont()->setBold(true);

// Set thin black border outline around column

$styleThinBlackBorderOutline = array(
    'borders' => array(
        'outline' => array(
            'style' => PHPExcel_Style_Border::BORDER_THIN,
            'color' => array('argb' => 'FF000000'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('A4:C' . ($row - 1))->applyFromArray($styleThinBlackBorderOutline);



$objPHPExcel->getActiveSheet()->getStyle('A1:C1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:C1')->getFill()->getStartColor()->setARGB('FF808080');

// Set style for header row using alternative method

$objPHPExcel->getActiveSheet()->getStyle('A3:C3')->applyFromArray(
        array(
            'font' => array(
                'bold' => true
            ),
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'top' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            ),
            'fill' => array(
                'type' => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
                'rotation' => 90,
                'startcolor' => array(
                    'argb' => 'FFA0A0A0'
                ),
                'endcolor' => array(
                    'argb' => 'FFFFFFFF'
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('A3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'left' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('B3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('C3')->applyFromArray(
        array(
            'borders' => array(
                'right' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);

// Add a drawing to the worksheet
// Set header and footer. When no different headers for odd/even are used, odd header is assumed.

$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddHeader('&L&BInvoice&RPrinted on &D');
$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');

// Set page orientation and size

$objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);
$objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);

// Rename first worksheet


$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Logo');
$objDrawing->setDescription('Logo');
$objDrawing->setPath('./images/logo.png');
$objDrawing->setHeight(36);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());




$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
$objWriter->save($rutaExcel);

echo ' <div class="alert bg-green alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                                Se ha creado el Excel de Reporte de Pasadia en la siguiente Ruta <strong>' . $rutaExcel . '</strong><br>
                                <a style="color:white;" href="' . Yii::$app->urlManager->createAbsoluteUrl('reportes/trabajadores') . '"><strong>Volver a Resportes Trabajadores</strong></a>
                            </div> ', EOL;
?>