<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\models\Agencia;
use frontend\models\ReservacionHab;
use frontend\models\Subservicios;
use frontend\models\Servicio;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model frontend\models\Reservacion */

$this->title = 'REPORTES DE SERVICIOS POR RESERVA';
$this->params['breadcrumbs'][] = ['label' => 'REPORTES', 'url' => ['agencia']];
$this->params['breadcrumbs'][] = $this->title;

?>

<?php

include 'lib/PHPExcel.php';
include 'lib/PHPExcel/Writer/Excel2007.php';

$objPHPExcel = new PHPExcel();

define('EOL',(PHP_SAPI == 'cli') ? PHP_EOL : '<br />');

$rutaExcel = 'd:/Factura_ServiciosxReserva.xlsx';

// Set document properties

$objPHPExcel->getProperties()->setCreator("Sistema de Reservas")
                             ->setLastModifiedBy("Sistema de Reservas")
                             ->setTitle("Generated by Sistema de Reservas v1.0")
                             ->setSubject("Office 2007 XLSX Test Document")
                             ->setDescription("Test document for Office 2007 XLSX, generated using PHP classes.")
                             ->setKeywords("office 2007 openxml php")
                             ->setCategory("Test result file");

// Create a first sheet, representing sales data

$objPHPExcel->setActiveSheetIndex(0);

$objPHPExcel->getActiveSheet()->setCellValue('B1', 'Factura');
$objPHPExcel->getActiveSheet()->setCellValue('D1', PHPExcel_Shared_Date::PHPToExcel( gmmktime(0,0,0,date('m'),date('d'),date('Y')) ));
$objPHPExcel->getActiveSheet()->getStyle('D1')->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_XLSX15);



$objPHPExcel->getActiveSheet()->setCellValue('G1', 'Factura');
$objPHPExcel->getActiveSheet()->setCellValue('I1', PHPExcel_Shared_Date::PHPToExcel( gmmktime(0,0,0,date('m'),date('d'),date('Y')) ));
$objPHPExcel->getActiveSheet()->getStyle('I1')->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_XLSX15);


$objPHPExcel->getActiveSheet()->setCellValue('L1', 'Factura');
$objPHPExcel->getActiveSheet()->setCellValue('N1', PHPExcel_Shared_Date::PHPToExcel( gmmktime(0,0,0,date('m'),date('d'),date('Y')) ));
$objPHPExcel->getActiveSheet()->getStyle('N1')->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_XLSX15);


//Header de la tabla habria que personalizarlo en depencia del reporte

$objPHPExcel->getActiveSheet()->setCellValue('A3', 'Servicio');
$objPHPExcel->getActiveSheet()->setCellValue('B3', 'Cantidad');
$objPHPExcel->getActiveSheet()->setCellValue('C3', 'Precio');
$objPHPExcel->getActiveSheet()->setCellValue('D3', 'Importe');

/*PRUEBA A VER */

$objPHPExcel->getActiveSheet()->setCellValue('F3', 'Service');
$objPHPExcel->getActiveSheet()->setCellValue('G3', 'Quantity');
$objPHPExcel->getActiveSheet()->setCellValue('H3', 'Prece');
$objPHPExcel->getActiveSheet()->setCellValue('I3', 'Amount');


$objPHPExcel->getActiveSheet()->setCellValue('K3', 'Service');
$objPHPExcel->getActiveSheet()->setCellValue('L3', 'Quantité');
$objPHPExcel->getActiveSheet()->setCellValue('M3', 'Prix');
$objPHPExcel->getActiveSheet()->setCellValue('N3', 'Montant');



$servxreservas=$todasserv[0];


$row = 4;
//echo count($alojamientos); die;
for($i=0; $i<count($servxreservas);$i++){

        $objPHPExcel->getActiveSheet()->setCellValue('A'.$row, $servxreservas[$i]['servicio']);
        $objPHPExcel->getActiveSheet()->setCellValue('B'.$row, $servxreservas[$i]['cantidad']);
        $objPHPExcel->getActiveSheet()->setCellValue('C'.$row, $servxreservas[$i]['precio']);
        $objPHPExcel->getActiveSheet()->setCellValue('D'.$row, $servxreservas[$i]['importe']);

$row++;

}

$servxreservas=$todasserv[1];
$row = 4;
//echo count($alojamientos); die;
for($i=0; $i<count($servxreservas);$i++){

        $objPHPExcel->getActiveSheet()->setCellValue('F'.$row, $servxreservas[$i]['servicio']);
        $objPHPExcel->getActiveSheet()->setCellValue('G'.$row, $servxreservas[$i]['cantidad']);
        $objPHPExcel->getActiveSheet()->setCellValue('H'.$row, $servxreservas[$i]['precio']);
        $objPHPExcel->getActiveSheet()->setCellValue('I'.$row, $servxreservas[$i]['importe']);

$row++;

}

$servxreservas=$todasserv[2];
$row = 4;
//echo count($alojamientos); die;
for($i=0; $i<count($servxreservas);$i++){

        $objPHPExcel->getActiveSheet()->setCellValue('K'.$row, $servxreservas[$i]['servicio']);
        $objPHPExcel->getActiveSheet()->setCellValue('L'.$row, $servxreservas[$i]['cantidad']);
        $objPHPExcel->getActiveSheet()->setCellValue('M'.$row, $servxreservas[$i]['precio']);
        $objPHPExcel->getActiveSheet()->setCellValue('N'.$row, $servxreservas[$i]['importe']);

$row++;

}

// Protect cells

$objPHPExcel->getActiveSheet()->getProtection()->setSheet(false);    // Needs to be set to true in order to enable any worksheet protection!
$objPHPExcel->getActiveSheet()->protectCells('A3:D'.$row, 'PHPExcel');



$objPHPExcel->getActiveSheet()->getProtection()->setSheet(false);    // Needs to be set to true in order to enable any worksheet protection!
$objPHPExcel->getActiveSheet()->protectCells('F3:I'.$row, 'PHPExcel');


$objPHPExcel->getActiveSheet()->getProtection()->setSheet(false);    // Needs to be set to true in order to enable any worksheet protection!
$objPHPExcel->getActiveSheet()->protectCells('K3:N'.$row, 'PHPExcel');

// Set cell number formats

$objPHPExcel->getActiveSheet()->getStyle('I4:D'.($row+2))->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);

$objPHPExcel->getActiveSheet()->getStyle('F4:I'.($row+2))->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);

$objPHPExcel->getActiveSheet()->getStyle('K4:N'.($row+2))->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);

// Set column widths

$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(28);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(20);



$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(28);
$objPHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('I')->setWidth(20);


$objPHPExcel->getActiveSheet()->getColumnDimension('K')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('L')->setWidth(28);
$objPHPExcel->getActiveSheet()->getColumnDimension('M')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('N')->setWidth(20);

// Set fonts

$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setName('Candara');
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setSize(20);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setUnderline(PHPExcel_Style_Font::UNDERLINE_SINGLE);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('D1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('E1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('D'.($row+2))->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('I'.($row+2))->getFont()->setBold(true);

// Set thin black border outline around column

$styleThinBlackBorderOutline = array(
    'borders' => array(
        'outline' => array(
            'style' => PHPExcel_Style_Border::BORDER_THIN,
            'color' => array('argb' => 'FF000000'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('A4:D'.($row-1))->applyFromArray($styleThinBlackBorderOutline);







$objPHPExcel->getActiveSheet()->getStyle('G1')->getFont()->setName('Candara');
$objPHPExcel->getActiveSheet()->getStyle('G1')->getFont()->setSize(20);
$objPHPExcel->getActiveSheet()->getStyle('G1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('G1')->getFont()->setUnderline(PHPExcel_Style_Font::UNDERLINE_SINGLE);
$objPHPExcel->getActiveSheet()->getStyle('G1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('I1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('E1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('I'.($row+2))->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('N'.($row+2))->getFont()->setBold(true);

// Set thin black border outline around column

$styleThinBlackBorderOutline = array(
    'borders' => array(
        'outline' => array(
            'style' => PHPExcel_Style_Border::BORDER_THIN,
            'color' => array('argb' => 'FF000000'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('F4:I'.($row-1))->applyFromArray($styleThinBlackBorderOutline);








$objPHPExcel->getActiveSheet()->getStyle('L1')->getFont()->setName('Candara');
$objPHPExcel->getActiveSheet()->getStyle('L1')->getFont()->setSize(20);
$objPHPExcel->getActiveSheet()->getStyle('L1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('L1')->getFont()->setUnderline(PHPExcel_Style_Font::UNDERLINE_SINGLE);
$objPHPExcel->getActiveSheet()->getStyle('L1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('N1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('L1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('L'.($row+2))->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('P'.($row+2))->getFont()->setBold(true);

// Set thin black border outline around column

$styleThinBlackBorderOutline = array(
    'borders' => array(
        'outline' => array(
            'style' => PHPExcel_Style_Border::BORDER_THIN,
            'color' => array('argb' => 'FF000000'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('K4:N'.($row-1))->applyFromArray($styleThinBlackBorderOutline);


// Set thick brown border outline around "Total"
/*
$styleThickBrownBorderOutline = array(
    'borders' => array(
        'outline' => array(
            'style' => PHPExcel_Style_Border::BORDER_THICK,
            'color' => array('argb' => 'FF993300'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('H'.($row+2).':I'.($row+2))->applyFromArray($styleThickBrownBorderOutline);
*/
// Set fills

$objPHPExcel->getActiveSheet()->getStyle('A1:D1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:D1')->getFill()->getStartColor()->setARGB('FF808080');



$objPHPExcel->getActiveSheet()->getStyle('F1:I1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('F1:I1')->getFill()->getStartColor()->setARGB('FF808080');


$objPHPExcel->getActiveSheet()->getStyle('K1:N1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('K1:N1')->getFill()->getStartColor()->setARGB('FF808080');




// Set style for header row using alternative method

$objPHPExcel->getActiveSheet()->getStyle('A3:D3')->applyFromArray(
        array(
            'font'    => array(
                'bold'      => true
            ),
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'top'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            ),
            'fill' => array(
                'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
                'rotation'   => 90,
                'startcolor' => array(
                    'argb' => 'FFA0A0A0'
                ),
                'endcolor'   => array(
                    'argb' => 'FFFFFFFF'
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('A3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'left'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('B3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('D3')->applyFromArray(
        array(
            'borders' => array(
                'right'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);


/* AQUI ES DONDE SE LE DA EL ESTILO A LA TABLA DEL EXCEL*/



$objPHPExcel->getActiveSheet()->getStyle('F3:I3')->applyFromArray(
        array(
            'font'    => array(
                'bold'      => true
            ),
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'top'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            ),
            'fill' => array(
                'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
                'rotation'   => 90,
                'startcolor' => array(
                    'argb' => 'FFA0A0A0'
                ),
                'endcolor'   => array(
                    'argb' => 'FFFFFFFF'
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('F3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'left'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('G3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('I3')->applyFromArray(
        array(
            'borders' => array(
                'right'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);








$objPHPExcel->getActiveSheet()->getStyle('K3:N3')->applyFromArray(
        array(
            'font'    => array(
                'bold'      => true
            ),
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'top'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            ),
            'fill' => array(
                'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
                'rotation'   => 90,
                'startcolor' => array(
                    'argb' => 'FFA0A0A0'
                ),
                'endcolor'   => array(
                    'argb' => 'FFFFFFFF'
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('K3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'left'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('L3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('N3')->applyFromArray(
        array(
            'borders' => array(
                'right'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);












// Add a drawing to the worksheet

$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Logo');
$objDrawing->setDescription('Logo');
$objDrawing->setPath('./images/logo.png');
$objDrawing->setHeight(36);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());



$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Logo');
$objDrawing->setDescription('Logo');
$objDrawing->setPath('./images/logo.png');
$objDrawing->setCoordinates('F1');
$objDrawing->setHeight(36);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());


$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Logo');
$objDrawing->setDescription('Logo');
$objDrawing->setPath('./images/logo.png');
$objDrawing->setCoordinates('K1');
$objDrawing->setHeight(36);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());







// Add a drawing to the worksheet

$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Paid');
$objDrawing->setDescription('Paid');
$objDrawing->setPath('./images/paid.png');
$objDrawing->setCoordinates('F50');
$objDrawing->setOffsetX(110);
$objDrawing->setRotation(25);
$objDrawing->getShadow()->setVisible(true);
$objDrawing->getShadow()->setDirection(45);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());

// Set header and footer. When no different headers for odd/even are used, odd header is assumed.

$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddHeader('&L&BInvoice&RPrinted on &D');
$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');

// Set page orientation and size

$objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);
$objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);

// Rename first worksheet

$objPHPExcel->getActiveSheet()->setTitle('Factura Español');





















$cont=0;



for($j=0;$j<count($hab);$j++){

    $todo=$hab[$j];
  

    $objPHPExcel->createSheet();

// Create a first sheet, representing sales data
$cont++;

$objPHPExcel->setActiveSheetIndex($cont);

// Create a first sheet, representing sales data


$objPHPExcel->getActiveSheet()->setCellValue('B1', 'Factura');
$objPHPExcel->getActiveSheet()->setCellValue('D1', PHPExcel_Shared_Date::PHPToExcel( gmmktime(0,0,0,date('m'),date('d'),date('Y')) ));
$objPHPExcel->getActiveSheet()->getStyle('D1')->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_XLSX15);



$objPHPExcel->getActiveSheet()->setCellValue('G1', 'Factura');
$objPHPExcel->getActiveSheet()->setCellValue('I1', PHPExcel_Shared_Date::PHPToExcel( gmmktime(0,0,0,date('m'),date('d'),date('Y')) ));
$objPHPExcel->getActiveSheet()->getStyle('I1')->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_XLSX15);


$objPHPExcel->getActiveSheet()->setCellValue('L1', 'Factura');
$objPHPExcel->getActiveSheet()->setCellValue('N1', PHPExcel_Shared_Date::PHPToExcel( gmmktime(0,0,0,date('m'),date('d'),date('Y')) ));
$objPHPExcel->getActiveSheet()->getStyle('N1')->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_XLSX15);


//Header de la tabla habria que personalizarlo en depencia del reporte

$objPHPExcel->getActiveSheet()->setCellValue('A3', 'Servicio');
$objPHPExcel->getActiveSheet()->setCellValue('B3', 'Cantidad');
$objPHPExcel->getActiveSheet()->setCellValue('C3', 'Precio');
$objPHPExcel->getActiveSheet()->setCellValue('D3', 'Importe');

/*PRUEBA A VER */

$objPHPExcel->getActiveSheet()->setCellValue('F3', 'Service');
$objPHPExcel->getActiveSheet()->setCellValue('G3', 'Quantity');
$objPHPExcel->getActiveSheet()->setCellValue('H3', 'Prece');
$objPHPExcel->getActiveSheet()->setCellValue('I3', 'Amount');


$objPHPExcel->getActiveSheet()->setCellValue('K3', 'Service');
$objPHPExcel->getActiveSheet()->setCellValue('L3', 'Quantité');
$objPHPExcel->getActiveSheet()->setCellValue('M3', 'Prix');
$objPHPExcel->getActiveSheet()->setCellValue('N3', 'Montant');

//Todo Esto se va
/*$objPHPExcel->getActiveSheet()->setCellValue('E3', 'Ocupacion');
$objPHPExcel->getActiveSheet()->setCellValue('F3', 'Plan');
$objPHPExcel->getActiveSheet()->setCellValue('G3', 'Precio');
$objPHPExcel->getActiveSheet()->setCellValue('H3', 'Noches');
$objPHPExcel->getActiveSheet()->setCellValue('I3', 'Importe');
*/

$servxreservas=$todo[0];


$row = 4;
//echo count($alojamientos); die;
for($i=0; $i<count($servxreservas);$i++){

        $objPHPExcel->getActiveSheet()->setCellValue('A'.$row, $servxreservas[$i]['servicio']);
        $objPHPExcel->getActiveSheet()->setCellValue('B'.$row, $servxreservas[$i]['cantidad']);
        $objPHPExcel->getActiveSheet()->setCellValue('C'.$row, $servxreservas[$i]['precio']);
        $objPHPExcel->getActiveSheet()->setCellValue('D'.$row, $servxreservas[$i]['importe']);

$row++;

}

$servxreservas=$todo[1];

$row = 4;
//echo count($alojamientos); die;
for($i=0; $i<count($servxreservas);$i++){

        $objPHPExcel->getActiveSheet()->setCellValue('F'.$row, $servxreservas[$i]['servicio']);
        $objPHPExcel->getActiveSheet()->setCellValue('G'.$row, $servxreservas[$i]['cantidad']);
        $objPHPExcel->getActiveSheet()->setCellValue('H'.$row, $servxreservas[$i]['precio']);
        $objPHPExcel->getActiveSheet()->setCellValue('I'.$row, $servxreservas[$i]['importe']);

$row++;

}

$servxreservas=$todo[2];

$row = 4;
//echo count($alojamientos); die;
for($i=0; $i<count($servxreservas);$i++){

        $objPHPExcel->getActiveSheet()->setCellValue('K'.$row, $servxreservas[$i]['servicio']);
        $objPHPExcel->getActiveSheet()->setCellValue('L'.$row, $servxreservas[$i]['cantidad']);
        $objPHPExcel->getActiveSheet()->setCellValue('M'.$row, $servxreservas[$i]['precio']);
        $objPHPExcel->getActiveSheet()->setCellValue('N'.$row, $servxreservas[$i]['importe']);

$row++;

}
$objPHPExcel->getActiveSheet()->getProtection()->setSheet(false);    // Needs to be set to true in order to enable any worksheet protection!
$objPHPExcel->getActiveSheet()->protectCells('A3:D'.$row, 'PHPExcel');



$objPHPExcel->getActiveSheet()->getProtection()->setSheet(false);    // Needs to be set to true in order to enable any worksheet protection!
$objPHPExcel->getActiveSheet()->protectCells('F3:I'.$row, 'PHPExcel');


$objPHPExcel->getActiveSheet()->getProtection()->setSheet(false);    // Needs to be set to true in order to enable any worksheet protection!
$objPHPExcel->getActiveSheet()->protectCells('K3:N'.$row, 'PHPExcel');

// Set cell number formats

$objPHPExcel->getActiveSheet()->getStyle('I4:D'.($row+2))->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);

$objPHPExcel->getActiveSheet()->getStyle('F4:I'.($row+2))->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);

$objPHPExcel->getActiveSheet()->getStyle('K4:N'.($row+2))->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_CURRENCY_USD_SIMPLE);

// Set column widths

$objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(28);
$objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(20);



$objPHPExcel->getActiveSheet()->getColumnDimension('F')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(28);
$objPHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('I')->setWidth(20);


$objPHPExcel->getActiveSheet()->getColumnDimension('K')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('L')->setWidth(28);
$objPHPExcel->getActiveSheet()->getColumnDimension('M')->setWidth(15);
$objPHPExcel->getActiveSheet()->getColumnDimension('N')->setWidth(20);

// Set fonts

$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setName('Candara');
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setSize(20);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->setUnderline(PHPExcel_Style_Font::UNDERLINE_SINGLE);
$objPHPExcel->getActiveSheet()->getStyle('B1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('D1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('E1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('D'.($row+2))->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('I'.($row+2))->getFont()->setBold(true);

// Set thin black border outline around column

$styleThinBlackBorderOutline = array(
    'borders' => array(
        'outline' => array(
            'style' => PHPExcel_Style_Border::BORDER_THIN,
            'color' => array('argb' => 'FF000000'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('A4:D'.($row-1))->applyFromArray($styleThinBlackBorderOutline);







$objPHPExcel->getActiveSheet()->getStyle('G1')->getFont()->setName('Candara');
$objPHPExcel->getActiveSheet()->getStyle('G1')->getFont()->setSize(20);
$objPHPExcel->getActiveSheet()->getStyle('G1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('G1')->getFont()->setUnderline(PHPExcel_Style_Font::UNDERLINE_SINGLE);
$objPHPExcel->getActiveSheet()->getStyle('G1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('I1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('E1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('I'.($row+2))->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('N'.($row+2))->getFont()->setBold(true);

// Set thin black border outline around column

$styleThinBlackBorderOutline = array(
    'borders' => array(
        'outline' => array(
            'style' => PHPExcel_Style_Border::BORDER_THIN,
            'color' => array('argb' => 'FF000000'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('F4:I'.($row-1))->applyFromArray($styleThinBlackBorderOutline);








$objPHPExcel->getActiveSheet()->getStyle('L1')->getFont()->setName('Candara');
$objPHPExcel->getActiveSheet()->getStyle('L1')->getFont()->setSize(20);
$objPHPExcel->getActiveSheet()->getStyle('L1')->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('L1')->getFont()->setUnderline(PHPExcel_Style_Font::UNDERLINE_SINGLE);
$objPHPExcel->getActiveSheet()->getStyle('L1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('N1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);
$objPHPExcel->getActiveSheet()->getStyle('L1')->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_WHITE);

$objPHPExcel->getActiveSheet()->getStyle('L'.($row+2))->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->getStyle('P'.($row+2))->getFont()->setBold(true);

// Set thin black border outline around column

$styleThinBlackBorderOutline = array(
    'borders' => array(
        'outline' => array(
            'style' => PHPExcel_Style_Border::BORDER_THIN,
            'color' => array('argb' => 'FF000000'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('K4:N'.($row-1))->applyFromArray($styleThinBlackBorderOutline);


// Set thick brown border outline around "Total"
/*
$styleThickBrownBorderOutline = array(
    'borders' => array(
        'outline' => array(
            'style' => PHPExcel_Style_Border::BORDER_THICK,
            'color' => array('argb' => 'FF993300'),
        ),
    ),
);
$objPHPExcel->getActiveSheet()->getStyle('H'.($row+2).':I'.($row+2))->applyFromArray($styleThickBrownBorderOutline);
*/
// Set fills

$objPHPExcel->getActiveSheet()->getStyle('A1:D1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('A1:D1')->getFill()->getStartColor()->setARGB('FF808080');



$objPHPExcel->getActiveSheet()->getStyle('F1:I1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('F1:I1')->getFill()->getStartColor()->setARGB('FF808080');


$objPHPExcel->getActiveSheet()->getStyle('K1:N1')->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID);
$objPHPExcel->getActiveSheet()->getStyle('K1:N1')->getFill()->getStartColor()->setARGB('FF808080');




// Set style for header row using alternative method

$objPHPExcel->getActiveSheet()->getStyle('A3:D3')->applyFromArray(
        array(
            'font'    => array(
                'bold'      => true
            ),
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'top'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            ),
            'fill' => array(
                'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
                'rotation'   => 90,
                'startcolor' => array(
                    'argb' => 'FFA0A0A0'
                ),
                'endcolor'   => array(
                    'argb' => 'FFFFFFFF'
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('A3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'left'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('B3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('D3')->applyFromArray(
        array(
            'borders' => array(
                'right'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);


/* AQUI ES DONDE SE LE DA EL ESTILO A LA TABLA DEL EXCEL*/



$objPHPExcel->getActiveSheet()->getStyle('F3:I3')->applyFromArray(
        array(
            'font'    => array(
                'bold'      => true
            ),
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'top'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            ),
            'fill' => array(
                'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
                'rotation'   => 90,
                'startcolor' => array(
                    'argb' => 'FFA0A0A0'
                ),
                'endcolor'   => array(
                    'argb' => 'FFFFFFFF'
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('F3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'left'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('G3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('I3')->applyFromArray(
        array(
            'borders' => array(
                'right'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);








$objPHPExcel->getActiveSheet()->getStyle('K3:N3')->applyFromArray(
        array(
            'font'    => array(
                'bold'      => true
            ),
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'top'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            ),
            'fill' => array(
                'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
                'rotation'   => 90,
                'startcolor' => array(
                    'argb' => 'FFA0A0A0'
                ),
                'endcolor'   => array(
                    'argb' => 'FFFFFFFF'
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('K3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            ),
            'borders' => array(
                'left'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('L3')->applyFromArray(
        array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_LEFT,
            )
        )
);

$objPHPExcel->getActiveSheet()->getStyle('N3')->applyFromArray(
        array(
            'borders' => array(
                'right'     => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN
                )
            )
        )
);












// Add a drawing to the worksheet

$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Logo');
$objDrawing->setDescription('Logo');
$objDrawing->setPath('./images/logo.png');
$objDrawing->setHeight(36);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());



$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Logo');
$objDrawing->setDescription('Logo');
$objDrawing->setPath('./images/logo.png');
$objDrawing->setCoordinates('F1');
$objDrawing->setHeight(36);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());


$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Logo');
$objDrawing->setDescription('Logo');
$objDrawing->setPath('./images/logo.png');
$objDrawing->setCoordinates('K1');
$objDrawing->setHeight(36);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());







// Add a drawing to the worksheet

$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('Paid');
$objDrawing->setDescription('Paid');
$objDrawing->setPath('./images/paid.png');
$objDrawing->setCoordinates('F50');
$objDrawing->setOffsetX(110);
$objDrawing->setRotation(25);
$objDrawing->getShadow()->setVisible(true);
$objDrawing->getShadow()->setDirection(45);
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());

// Set header and footer. When no different headers for odd/even are used, odd header is assumed.

$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddHeader('&L&BInvoice&RPrinted on &D');
$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');

// Set page orientation and size

$objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);
$objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);



$objPHPExcel->getActiveSheet()->setTitle('Factura '.$hab[$j][0][1]['servicio']);  
  
}





// Set active sheet index to the first sheet, so Excel opens this as the first sheet
$objPHPExcel->setActiveSheetIndex(0);






$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
$objWriter->save($rutaExcel);

echo ' <div class="alert bg-green alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                                Se ha creado el Excel de Reporte Agencia en la siguiente Ruta <strong>'.$rutaExcel.'</strong><br>
                                <a style="color:white;" href="' . Yii::$app->urlManager->createAbsoluteUrl('reportes/agencia') . '"><strong>Volver a Resportes Agencias</strong></a>
                            </div> ' , EOL;



?>